<?php

class PxlTabVertical_Widget extends Pxltheme_Core_Widget_Base{
    protected $name = 'pxl_tab_vertical';
    protected $title = 'PXL Tab Vertical';
    protected $icon = 'eicon-price-list';
    protected $categories = array( 'pxltheme-core' );
    protected $params = '{"sections":[{"name":"layout_section","label":"Layout","tab":"layout","controls":[{"name":"layout","label":"Layout","type":"layoutcontrol","default":"1","options":{"1":{"label":"Layout 1","image":"http:\/\/localhost\/theme_dith\/wp-content\/themes\/optione\/elements\/assets\/layout-image\/pxl_price_list-1.jpg"}},"prefix_class":"pxl-tabs-layout-"}]},{"name":"content_section","label":"Content","tab":"content","controls":[{"name":"content_to_show","label":"Content Show","type":"number","default":1},{"name":"tabs_list","label":"Tabs List","type":"repeater","controls":[{"name":"tab_title","label":"Title","type":"text","label_block":true},{"name":"content_type","label":"Content Type","type":"select","options":{"df":"Default","template":"From Template Builder"},"default":"df"},{"name":"content_template","label":"Select Templates","description":"Please create your layout before choosing. <a href=\"http:\/\/localhost\/theme_dith\/wp-admin\/edit.php?post_type=pxl-template\">Click Here<\/a>","type":"select","options":{"0":"None","701":"test"},"default":"df","condition":{"content_type":"template"}},{"name":"tab_content","label":"Enter Content","type":"wysiwyg","default":"","condition":{"content_type":"df"}}],"title_field":"{{{ tab_title }}}"},{"name":"title_background","label":"Title Background","type":"color","selectors":{"{{WRAPPER}} .pxl-tabs .tab-title":"background-color: {{VALUE}};"}},{"name":"title_active_background","label":"Active Background","type":"color","selectors":{"{{WRAPPER}} .pxl-tabs .tab-title.active":"background-color: {{VALUE}}; border-color: {{VALUE}};"}},{"name":"title_color","label":"Title Color","type":"color","selectors":{"{{WRAPPER}} .tab-title":"color: {{VALUE}};"}},{"name":"content_color","label":"Content Color","type":"color","selectors":{"{{WRAPPER}} .tab-content":"color: {{VALUE}};"}},{"name":"title_alignment","label":"Title Alignment","type":"choose","control_type":"responsive","options":{"start":{"title":"Start","icon":"eicon-text-align-left"},"center":{"title":"Center","icon":"eicon-text-align-center"},"end":{"title":"End","icon":"eicon-text-align-right"}},"selectors":{"{{WRAPPER}} .pxl-tabs .tabs-title":"justify-content: {{VALUE}};"}}]}]}';
    protected $styles = array(  );
    protected $scripts = array( 'optione-list-tabs' );
}