<?php

class PxlPriceList_Widget extends Pxltheme_Core_Widget_Base{
    protected $name = 'pxl_price_list';
    protected $title = 'PXL Price List';
    protected $icon = 'eicon-post-list';
    protected $categories = array( 'pxltheme-core' );
    protected $params = '{"sections":[{"name":"layout_section","label":"Layout","tab":"layout","controls":[{"name":"layout","label":"Layout","type":"layoutcontrol","default":"1","options":{"1":{"label":"Layout 1","image":"http:\/\/localhost\/theme_dith\/wp-content\/themes\/optione\/elements\/assets\/layout-image\/pxl_price-1.jpg"}},"prefix_class":"pxl-price-list-layout-"}]},{"name":"section_list","label":"Content","tab":"content","controls":[{"name":"content_list","label":"Testimonial Items","type":"repeater","default":[],"controls":[{"name":"title","label":"Title","type":"text","label_block":true},{"name":"description","label":"Description","type":"textarea","rows":10},{"name":"pricing_price_currency","label":"Currency","type":"text","default":"$","label_block":true},{"name":"pricing_price_value","label":"Price","type":"text","default":"25","label_block":true}],"title_field":"{{{ title }}}"}]},{"name":"style_section","label":"Style","tab":"content","controls":[{"name":"bg_color","label":"Background Color","type":"color","selectors":{"{{WRAPPER}} .pxl-price-list":"background-color: {{VALUE}};"}},{"name":"max_width","label":"Max Width Description(px)","type":"slider","control_type":"responsive","range":{"px":{"min":100,"max":1920}},"selectors":{"{{WRAPPER}} .item-desc":"max-width: {{SIZE}}{{UNIT}};"}},{"name":"item_padding","label":"Padding","type":"dimensions","control_type":"responsive","size_units":["px","em","%"],"selectors":{"{{WRAPPER}} .pxl-price-list .item-inner":"padding: {{TOP}}{{UNIT}} {{RIGHT}}{{UNIT}} {{BOTTOM}}{{UNIT}} {{LEFT}}{{UNIT}};"}},{"name":"border_width","label":"Border Width","type":"dimensions","selectors":{"{{WRAPPER}} .pxl-price-list .item-inner":"border-width: {{TOP}}{{UNIT}} {{RIGHT}}{{UNIT}} {{BOTTOM}}{{UNIT}} {{LEFT}}{{UNIT}};"},"responsive":true},{"name":"border_price_color","label":"Border Pricing Color","type":"color","selectors":{"{{WRAPPER}} .pxl-price-list .item-inner":"border-color: {{VALUE}};"}},{"name":"title_color","label":"Title Color","type":"color","selectors":{"{{WRAPPER}} .pxl-price-list .title-price .item-title":"color: {{VALUE}};"}},{"name":"price_color","label":"Price Color","type":"color","selectors":{"{{WRAPPER}} .pxl-price-list .title-price .pricing-price-value":"color: {{VALUE}};"}},{"name":"description_color","label":"Description Color","type":"color","selectors":{"{{WRAPPER}} .pxl-price-list .item-desc":"color: {{VALUE}};"}}]}]}';
    protected $styles = array(  );
    protected $scripts = array( 'swiper','optione-swiper' );
}