<?php

class PxlAccordion_Widget extends Pxltheme_Core_Widget_Base{
    protected $name = 'pxl_accordion';
    protected $title = 'PXL Accordion';
    protected $icon = 'eicon-accordion';
    protected $categories = array( 'pxltheme-core' );
    protected $params = '{"sections":[{"name":"source_section","label":"Source Settings","tab":"content","controls":[{"name":"style","label":"Style","type":"select","options":{"style1":"Style 1","style2":"Style 2","style3":"Style 3","style4":"Style 4"},"default":"style1"},{"name":"active_section","label":"Active section","type":"number","separator":"after","default":"1"},{"name":"ac_items","label":"Accordion Items","type":"repeater","controls":[{"name":"ac_title","label":"Title","type":"textarea","rows":3},{"name":"ac_content_type","label":"Content Type","type":"select","default":"text_editor","options":{"text_editor":"Text Editor","template":"Template"}},{"name":"ac_content","label":"Content","type":"wysiwyg","show_label":false,"condition":{"ac_content_type":"text_editor"}},{"name":"ac_content_template","label":"Select Templates","description":"Please create your layout before choosing. <a href=\"http:\/\/localhost\/theme_dith\/wp-admin\/edit.php?post_type=pxl-template\">Click Here<\/a>","type":"select","default":"","options":["None"],"condition":{"ac_content_type":"template"}}],"default":[{"ac_title":"FAQ Title #1","ac_content":"Lorem ipsum dolor sit amet consecte tur adipiscing elit sed do eiu smod tempor incididunt ut labore."},{"ac_title":"FAQ Title #2","ac_content":"Lorem ipsum dolor sit amet consecte tur adipiscing elit sed do eiu smod tempor incididunt ut labore."}],"title_field":"{{{ ac_title }}}","separator":"after"}]},{"name":"style_section","label":"Style","tab":"style","controls":[{"name":"title_color","label":"Title Color","type":"color","selectors":{"{{WRAPPER}} .pxl-accordion .ac-item .ac-title":"color: {{VALUE}};"}},{"name":"title_typography","label":"Title Typography","type":"typography","control_type":"group","selector":"{{WRAPPER}} .pxl-accordion .ac-item .ac-title"},{"name":"desc_color","label":"Description Color","type":"color","selectors":{"{{WRAPPER}} .pxl-accordion .ac-item .ac-desc":"color: {{VALUE}};"}},{"name":"desc_typography","label":"Description Typography","type":"typography","control_type":"group","selector":"{{WRAPPER}} .pxl-accordion .ac-item .ac-desc"}]}]}';
    protected $styles = array(  );
    protected $scripts = array( 'optione-accordion' );
}