<?php

class PxlContactForm_Widget extends Pxltheme_Core_Widget_Base{
    protected $name = 'pxl_contact_form';
    protected $title = 'Pxl Contact Form 7';
    protected $icon = 'eicon-form-horizontal';
    protected $categories = array( 'pxltheme-core' );
    protected $params = '{"sections":[{"name":"source_section","label":"Source Settings","tab":"content","controls":[{"name":"ctf7_slug","label":"Select Form","type":"select","options":{"contact-form-1":"Contact form 1"},"default":"contact-form-1"}]},{"name":"section_style_button","label":"Button Style","tab":"style","controls":[{"name":"button_space","label":"Margin(px)","type":"dimensions","allowed_dimensions":"vertical","default":{"top":"","right":"","bottom":"","left":""},"control_type":"responsive","size_units":["px"],"selectors":{"{{WRAPPER}} form button":"margin: {{TOP}}{{UNIT}} {{RIGHT}}{{UNIT}} {{BOTTOM}}{{UNIT}} {{LEFT}}{{UNIT}};"}},{"name":"text_align","label":"Alignment","type":"choose","control_type":"responsive","options":{"left":{"title":"Left","icon":"eicon-text-align-left"},"center":{"title":"Center","icon":"eicon-text-align-center"},"right":{"title":"Right","icon":"eicon-text-align-right"}},"selectors":{"{{WRAPPER}} .pxl-contact-form7":"text-align: {{VALUE}};"}},{"name":"button_width","label":"Button Width (%)","type":"slider","control_type":"responsive","range":{"px":{"min":0,"max":100}},"selectors":{"{{WRAPPER}} .pxl-contact-form7 button":"width: {{SIZE}}%;"}},{"name":"button_style_tabs","control_type":"tab","tabs":[{"name":"button_style_normal","label":"Normal","controls":[{"name":"button_color","label":"Text Color","type":"color","selectors":{"{{WRAPPER}} .wpcf7-form input[type=\"submit\"]":"color: {{VALUE}};"}},{"name":"button_background","type":"background","control_type":"group","types":["classic","gradient"],"selector":"{{WRAPPER}} .wpcf7-form input[type=\"submit\"]"}]},{"name":"button_style_hover","label":"Hover","controls":[{"name":"button_color_hover","label":"Text Color","type":"color","selectors":{"{{WRAPPER}} .wpcf7-form input[type=\"submit\"]:hover":"color:{{VALUE}};"}},{"name":"button_background_hover","type":"background","control_type":"group","types":["classic","gradient"],"selector":"{{WRAPPER}} .wpcf7-form input[type=\"submit\"]:hover"}]}]}]},{"name":"textarea_size","label":"Texarea Size","tab":"style","controls":[{"name":"message_height","type":"slider","label":"Message Height","size_units":["px"],"range":{"px":{"min":120,"max":350}},"default":{"unit":"px","size":""},"selectors":{"{{WRAPPER}} .wpcf7-form textarea.wpcf7-textarea":"height: {{SIZE}}{{UNIT}};"}}]}]}';
    protected $styles = array(  );
    protected $scripts = array(  );
}