<?php

class PxlAnchor_Widget extends Pxltheme_Core_Widget_Base{
    protected $name = 'pxl_anchor';
    protected $title = 'PXL Anchor';
    protected $icon = 'eicon-anchor';
    protected $categories = array( 'pxltheme-core' );
    protected $params = '{"sections":[{"name":"icon_section","label":"Settings","tab":"content","controls":[{"name":"template","label":"Select Templates","type":"select","options":{"0":"None","29":"Search page"},"default":"df"},{"name":"icon_type","label":"Select Icon Type","type":"select","options":{"none":"None","lib":"Library","custom":"Custom"},"default":"lib"},{"name":"selected_icon","label":"Icon","type":"icons","default":{"library":"pxli","value":"pxli-search-400"},"condition":{"icon_type":"lib"}},{"name":"icon_size","label":"Icon Size(px)","type":"slider","range":{"px":{"min":15,"max":300}},"condition":{"icon_type":"lib"},"selectors":{"{{WRAPPER}} .pxl-anchor-icon":"font-size: {{SIZE}}{{UNIT}};","{{WRAPPER}} .pxl-anchor-icon svg":"width: {{SIZE}}{{UNIT}};"}},{"name":"icon_margin","label":"Icon Margin(px)","type":"dimensions","control_type":"responsive","size_units":["px"],"selectors":{"{{WRAPPER}} .pxl-anchor-icon":"margin: {{TOP}}{{UNIT}} {{RIGHT}}{{UNIT}} {{BOTTOM}}{{UNIT}} {{LEFT}}{{UNIT}};"},"condition":{"icon_type!":"none"}},{"name":"title","label":"Title","type":"textarea","placeholder":"Menu"},{"name":"title_typo","label":"Title Typography","type":"typography","control_type":"group","selector":"{{WRAPPER}} .anchor-title","condition":{"title!":""}},{"name":"icon_color","label":"Color","type":"color","selectors":{"{{WRAPPER}} .pxl-anchor":"color: {{VALUE}};","{{WRAPPER}} .pxl-anchor-wrap .pxl-anchor-icon.custom span":"background-color: {{VALUE}};","{{WRAPPER}} .pxl-anchor-icon svg":"fill: {{VALUE}};"}},{"name":"icon_color_hover","label":"Hover Color","type":"color","selectors":{"{{WRAPPER}} .pxl-anchor:hover":"color: {{VALUE}};","{{WRAPPER}} .pxl-anchor-wrap .pxl-anchor-icon.custom.pxl-bars:hover span":"background-color: {{VALUE}};","{{WRAPPER}} .pxl-anchor:hover pxl-anchor-icon svg":"fill: {{VALUE}};"}},{"name":"align","label":"Alignment","type":"choose","control_type":"responsive","options":{"start":{"title":"Start","icon":"eicon-text-align-left"},"center":{"title":"Center","icon":"eicon-text-align-center"},"end":{"title":"End","icon":"eicon-text-align-right"}},"selectors":{"{{WRAPPER}} .pxl-anchor-wrap":"justify-content: {{VALUE}};"}},{"name":"custom_class","label":"Custom class","type":"text"}]}]}';
    protected $styles = array(  );
    protected $scripts = array(  );
}