<?php

class PxlTestimonialList_Widget extends Pxltheme_Core_Widget_Base{
    protected $name = 'pxl_testimonial_list';
    protected $title = 'PXL Testimonial List';
    protected $icon = 'eicon-blockquote';
    protected $categories = array( 'pxltheme-core' );
    protected $params = '{"sections":[{"name":"layout_section","label":"Layout","tab":"layout","controls":[{"name":"layout","label":"Layout","type":"layoutcontrol","default":"1","options":{"1":{"label":"Layout 1","image":"http:\/\/localhost\/theme_dith\/wp-content\/themes\/optione\/elements\/assets\/layout-image\/pxl_testimonial_list-1.jpg"}},"prefix_class":"pxl-testimonial-list-layout-"}]},{"name":"section_list","label":"Content","tab":"content","controls":[{"name":"content_list","label":"Testimonial Items","type":"repeater","default":[],"controls":[{"name":"image","label":"Image","type":"media"},{"name":"name","label":"Name","type":"text","label_block":true},{"name":"position","label":"Position","type":"text"},{"name":"title","label":"Title","type":"text","label_block":true},{"name":"description","label":"Description","type":"textarea","rows":10},{"name":"rating","label":"Rating","type":"select","default":"none","options":{"none":"None","star1":"1 Star","star2":"2 Star","star3":"3 Star","star4":"4 Star","star5":"5 Star"}}],"title_field":"{{{ title }}}"}]},{"name":"style_section","label":"Style","tab":"content","controls":[{"name":"quote_icon","label":"Quote Icon","type":"icons","fa4compatibility":"icon","condition":{"layout":"2"}},{"name":"bg_color","label":"Background Color","type":"color","selectors":{"{{WRAPPER}} .pxl-testimonial-list-item":"background-color: {{VALUE}};"}},{"name":"max_width","label":"Max Width Description(px)","type":"slider","control_type":"responsive","range":{"px":{"min":100,"max":1920}},"selectors":{"{{WRAPPER}} .item-desc":"max-width: {{SIZE}}{{UNIT}};"}},{"name":"title_color","label":"Title Color","type":"color","selectors":{"{{WRAPPER}} .pxl-testimonial-list-item .item-title":"color: {{VALUE}} !important;"}},{"name":"name_color","label":"Name Color","type":"color","selectors":{"{{WRAPPER}} .pxl-testimonial-list-item .item-name":"color: {{VALUE}} !important;"}},{"name":"position_color","label":"Position Color","type":"color","selectors":{"{{WRAPPER}} .pxl-testimonial-list-item .item-position":"color: {{VALUE}} !important;"}},{"name":"description_color","label":"Description Color","type":"color","selectors":{"{{WRAPPER}} .pxl-testimonial-list-item .item-desc":"color: {{VALUE}} !important;"}}]}]}';
    protected $styles = array(  );
    protected $scripts = array( 'swiper','optione-swiper' );
}